name: bread_delivery
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  share: ^2.0.4
  equatable: ^2.0.3
  flutter_bloc: ^7.1.0
  freezed: ^0.14.2
  geolocator: ^7.4.0
  get_it: ^7.2.0
  path_provider: ^2.0.2
  qrscan: ^0.3.2
  qr_flutter: ^4.0.0
  permission_handler: ^8.1.4+2
  shared_preferences: ^2.0.6
  zsdk: ^2.0.0+11
  charts_flutter: ^0.11.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  fluttertoast: ^8.0.8
  flutter_map: any
  flutter_map_location_marker: any
  flutter_map_marker_cluster: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  # - assets/icon/cuida.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icon/iconC.jpg"
  adaptive_icon_foreground: "assets/icon/iconC.jpg"
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#000000"
